### ISSUE TITLE
Bundle size increased a lot between 2.0.1 and 2.0.2

### ISSUE THREAD

**Issue by sebastianljunggren** [js-joda/js-joda-timezone#75]
When upgrading to 2.0.2 in my Angular project I noticed that my bundle size increased quite a bit.

According to https://bundlephobia.com/result?p=js-joda-timezone@2.0.2 the the size went from 183 to 910 kB (without gzip) which seems like a lot for what only seems to be an upgrade of the time zone database.

I'm creating this issue since I'm not aware if  this increase is intended or if some step in the upgrade of the database was missed.

**Comment by pithu** [comment]
The issue is caused by a fix in moment-timezone see https://github.com/moment/moment-timezone/blob/c377ac8fd7ff6c2fc52e2f432034ac5727dba1d8/changelog.md#0522-2018-10-28. Since that release the packed tzdb data file got much bigger, see https://bundlephobia.com/result?p=moment-timezone@0.5.25

js-joda-timezone is using the packed version from moment-timezone, so we get the same effect here. I am not 100 percent sure, but i guess the bigger size is just because of more accurate data, so nothing what could be fixed.

Fortunately (thx to @JKillian #73), since the last release today (version 2.1.0) we have smaller javascript bundles that contains only a subset of the tzdb data for a certain range of years. Currently we support the same ranges as moment-time-zone:

bundle | size
-- | --
all | 911 KB
10-year-range | 34 KB
1970 - 2030 | 150 KB
2012 - 2022 | 34 KB

So if its an option for you, you could use one of the subsets.

**Comment by sebastianljunggren** [comment]
Thank you for the quick reply and new release! One of the smaller bundles are fine for my use case.
